name: Deploy Frontend OCI

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-web:latest .
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-web:latest

      - name: Deploy to OCI via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_VM_IP_FRONT }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY_FRONT }}
          script: |
            mkdir -p ~/clinicamedagil-web
            cd ~/clinicamedagil-web

            cat <<EOF > docker-compose.yml
            services:
              web:
                image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/clinicamedagil-web:latest
                container_name: frontend
                ports:
                  - "80:80"
                restart: always
            EOF

            sudo docker compose pull
            sudo docker compose up -d
